apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose/docker-compose.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gobel-client-example
  name: gobel-client-example
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gobel-client-example
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose/docker-compose.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/gobel_link: "true"
        io.kompose.service: gobel-client-example
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://gobel-api:82
            - name: LOG_THRESHOLD
              value: "1"
            - name: LOG_TIME_ZONE_OFFSET
              value: "32400"
            - name: SERVER_PORT
              value: "81"
            - name: SITE_URL
              value: http://localhost:81
            - name: TIME_ZONE
              value: Asia/Tokyo
          image: gobel-client-example
          name: gobel-client-example
          ports:
            - containerPort: 81
          resources: {}
      restartPolicy: Always
status: {}
