apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose/docker-compose.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqld-exporter
  name: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqld-exporter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose/docker-compose.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/gobel_link: "true"
        io.kompose.service: mysqld-exporter
    spec:
      containers:
        - args:
            - --collect.global_status
            - --collect.global_variables
            - --collect.slave_status
            - --collect.binlog_size
            - --collect.info_schema.processlist
            - --collect.info_schema.userstats
            - --collect.info_schema.tables
            - --collect.auto_increment.columns
            - --collect.info_schema.tablestats
            - --collect.perf_schema.file_events
            - --collect.perf_schema.eventsstatements
            - --collect.perf_schema.indexiowaits
            - --collect.perf_schema.tableiowaits
            - --collect.perf_schema.tablelocks
            - --collect.perf_schema.eventswaits
          env:
            - name: DATA_SOURCE_NAME
              value: root:password@(localhost:3306)/
          image: mysqld-exporter
          name: gobel-mysqld-exporter
          ports:
            - containerPort: 9104
          resources: {}
      restartPolicy: Always
status: {}
