server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://${GOBEL_ELASTICSEARCH_CONTAINER_NAME}:${GOBEL_ELASTICSEARCH_CONTAINER_PORT}" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.username: ${GOBEL_ELASTICSEARCH_ELASTIC_USERNAME}
elasticsearch.password: ${GOBEL_ELASTICSEARCH_ELASTIC_PASSWORD}