apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gobel-client-example
  name: gobel-client-example
spec:
  ports:
    - name: "81"
      port: 81
      targetPort: 81
  selector:
    io.kompose.service: gobel-client-example
status:
  loadBalancer: {}
