apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: node-exporter
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/gobel_link: "true"
        io.kompose.service: node-exporter
    spec:
      containers:
        - args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
          image: node-exporter
          name: gobel-node-exporter
          ports:
            - containerPort: 9100
          resources: {}
          volumeMounts:
            - mountPath: /host/proc
              name: node-exporter-claim0
            - mountPath: /host/sys
              name: node-exporter-claim1
            - mountPath: /rootfs
              name: node-exporter-claim2
      restartPolicy: Always
      volumes:
        - name: node-exporter-claim0
          persistentVolumeClaim:
            claimName: node-exporter-claim0
        - name: node-exporter-claim1
          persistentVolumeClaim:
            claimName: node-exporter-claim1
        - name: node-exporter-claim2
          persistentVolumeClaim:
            claimName: node-exporter-claim2
status: {}
