apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-insight
  name: redis-insight
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-insight
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/gobel_link: "true"
        io.kompose.service: redis-insight
    spec:
      containers:
        - image: redis-insight
          name: gobel-redis-insight
          ports:
            - containerPort: 8001
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/redis-insight
              name: redis-insight-claim0
      restartPolicy: Always
      volumes:
        - name: redis-insight-claim0
          persistentVolumeClaim:
            claimName: redis-insight-claim0
status: {}
